# create your drupal and postgres config here, based off the last assignment
version: '2'

services:  # containers. same as docker run
  drupal: # a friendly name. this is also DNS name inside network
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-drupal
#    image: drupal:latest # Optional if you use build:
    ports: 
      - '8080:80'
    volumes: # Optional, same as -v in docker run
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites 
    restart: always

  postgres:
    image: postgres:9.6
    environment:  #if don't specify POSTGRESS_DB, the default value for db username will be 'postgres'
      POSTGRES_PASSWORD: testing123
    volumes: 
      - drupal-data:/var/lib/postgresql/data
    restart: always

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  drupal-data:
  