# create your drupal and postgres config here, based off the last assignment
version: '3.1'

services:  # containers. same as docker run
  drupal: # a friendly name. this is also DNS name inside network
    build: .
#    image: drupal:latest # Optional if you use build:
    ports: 
      - '8080:80'
    volumes: # Optional, same as -v in docker run
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites 

  postgres:
    environment:  #if don't specify POSTGRESS_DB, the default value for db username will be 'postgres'
      - POSTGRES_PASSWORD_FILE:/run/secrets/psql-pw
    secrets:
      - psql-pw
    volumes: 
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  drupal-data:

secrets:
  psql-pw:
    file: psql-fake-password.txt